services:
  next-pizza:
    container_name: next-pizza-prod
    build:
      context: .
      target: production
    image: bering152/next-pizza-prod:latest
    env_file:
      - .env.production

    ports:
      - "3000:3000"
