import { Container, Header } from "@/src/components/shared";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Pizza | Cart",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense><Header hasSearch={false} hasCart={false} className="border-gray-200" /></Suspense>
        {children}
      </Container>
    </main>
  );
}
